In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib

# Load the dataset
music_data = pd.read_csv('/content/drive/MyDrive/Github/music.csv')
music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [29]:
X = music_data.drop(columns=['genre'])
X

    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [30]:
y = music_data['genre']
y

0        HipHop
1        HipHop
2        HipHop
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10        Dance
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
Name: genre, dtype: object

In [31]:
model = DecisionTreeClassifier()
model.fit(X,y)
music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [32]:
# The tree helped us understand that younger men from 20 - 25 is hip hop
# Males between 26 - 30 is jazz
# females 20 - 25 is Dance
# females 26 - 30 is Acoustic
predictions = model.predict([ [21, 1], [22,0] ])
predictions

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['HipHop', 'Dance'], dtype=object)

In [34]:
# Calculating accuracy
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
model.fit(X_train, y_train)
predictions = model.predict(X_test)

joblib.dump(model, 'music-recommender.hoblib') # job live file, so we dont have to train the model every time
score = accuracy_score(y_test, predictions)
score
#note with every run the accuracy will drop from 1 to 0.75 to even 0.5 due to the size of our data

1.0

In [35]:
model = joblib.load('music-reccomender.joblib')
predictions = model.predict([[21,1]])
predictions

NameError: name 'joblib' is not defined

In [41]:
# Visualizing a Decision Tree

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

music_data = pd.read_csv('/content/drive/MyDrive/Github/music.csv')
X = music_data.drop(columns=['genre'])
y = music_data['genre']

model = DecisionTreeClassifier()
model.fit(X,y)

tree.export_graphviz(model, out_file='music-recommendor.dot',
                    feature_names=['age', 'gender'],
                    class_names=sorted(y.unique()),
                    label='all',
                    rounded=True,
                    filled=True)